# Generated by Django 3.1.5 on 2021-01-16 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Зірка рейтингу', 'verbose_name_plural': 'Зірки рейтингу'},
        ),
    ]
